services:
  db:
    image: postgres:latest
    container_name: weblog-backend-db
    environment:
      POSTGRES_USER: webloguser
      POSTGRES_PASSWORD: QyfOJs4xwsh6qdlv
      POSTGRES_DB: weblog
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: